name: Metrics
# GitHub metrics as SVG image
on:
  # Schedule updates
  schedule: [{ cron: "0 * * * *" }]
  push: { branches: ["master", "main"] }
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          base: header, activity, community, repositories, metadata
          config_timezone: America/New_York
          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year
          plugin_languages: true
          plugin_languages_ignored: PHP, Tcl, Batchfile, mcfunction, Mathematica, rtf
          plugin_languages_details: percentage
          plugin_introduction: true
          plugin_introduction_title: true
          repositories_forks: true
